### ISSUE TITLE
Error on send_message_to_channel

### ISSUE THREAD

**Issue by alexferra** [Jacoblightning/discord-sender#3]
it worked correctly 2-3 times then this:

  user.send_message_to_channel(
 
  File "C:\Users\Alefe\AppData\Roaming\Python\Python311\site-packages\discord_sender\discord.py", line 193, in send_message_to_channel
    self._handle_error(response)
  File "C:\Users\Alefe\AppData\Roaming\Python\Python311\site-packages\discord_sender\discord.py", line 125, in _handle_error
    raise requests.RequestException(
requests.exceptions.RequestException: Unknown error code from discord. Json data: {'message': 'Unknown Message', 'code': 10008}

**Comment by Jacoblightning** [comment]
I don't think that there is anything I can do about this as discord is returning an error and not being very descriptive. The module is coded so that any unknown errors are passed through so discord is giving the error "Unknown message". If I am able to recreate this issue, I will attempt to fix it but right now I have no idea what could be causing it.
